### ISSUE TITLE
Kontakt?

### ISSUE THREAD

**Issue by jkrybicki** [philvec/sentimentPL#4]
Szanowny Panie,
Przepraszam, że porozumiewam się z Panem w ten sposób, ale jak inaczej. Odkryłem Pana sentimentPL i używam go do analizy wydźwięku zgromadzonych przeze mnie 10000 polskich tekstów literackich (pełne powieści, dramaty, zbiorki poezji). Jak rozumiem, nie jest to całkiem pozbawione sensu, bo trenował Pan model na "Wolnych lekturach". Z przyjemnościa poznałbym więcej szczegółów - może moglibyśmy umówić się na jakąś rozmowę, bo wydaje mi się, że wyniki mogą być całkiem publikowalne? 
Z serdecznymi pozdrowieniami,
Jan Rybicki
Jagiellońskie Centrum Humanistyki Cyfrowej 
https://www.uj.edu.pl/web/jchc

**Comment by TheOffiec** [comment]
Dzień dobry, zupełnie nie rozumiem dlaczego wszyscy zakładają łącznie z promotorem ze jestem facetem (dzień przed obroną chyba odkrył ze jestem kobietą) ;) istotnie ruszyłam SentimentPl ale ostatecznie go nie użyłam i zdecydowałam się na slowosieć, której wyniki i tak przedstawiłam bardziej jako ciekawostkę. Z SentimentPl miałam problem w interpretacji wyniku jeśli dobrze pamietam, ale nie pamietam czy udało mi się dotrzeć do dokumentacji, na podobnej pracy zauważyłam ze autorzy którzy skorzystali z SentimentPl  większość analizowanych słów zakwalifikowali jako słowa negatywne - prawdopodobnie brak dokumentacji.  Temat analizy języka dopiero zaczynam zgłębiać wiec prawdopodobnie mogłam coś przeoczyć ;)Z pozdrowieniamiMarta KliszkoWysłane z iPhone'aWiadomość napisana przez Jan Rybicki ***@***.***> w dniu 19.07.2023, o godz. 07:17:﻿
Szanowny Panie,
Przepraszam, że porozumiewam się z Panem w ten sposób, ale jak inaczej. Odkryłem Pana sentimentPL i używam go do analizy wydźwięku zgromadzonych przeze mnie 10000 polskich tekstów literackich (pełne powieści, dramaty, zbiorki poezji). Jak rozumiem, nie jest to całkiem pozbawione sensu, bo trenował Pan model na "Wolnych lekturach". Z przyjemnościa poznałbym więcej szczegółów - może moglibyśmy umówić się na jakąś rozmowę, bo wydaje mi się, że wyniki mogą być całkiem publikowalne?
Z serdecznymi pozdrowieniami,
Jan Rybicki
Jagiellońskie Centrum Humanistyki Cyfrowej
https://www.uj.edu.pl/web/jchc

**Comment by jkrybicki** [comment]
[WybuchWMózgu]
Ten zarośnięty typ podpisany “Filip Strzałka” jest kobietą Martą Kliszko?! Wiem, że jestem człowiekiem starej daty (ur. 1963), ale żeby aż tak?

Co się dzieje?

Wstrząśnięty,

Jan Rybicki

**Comment by TheOffiec** [comment]
Najwyraźniej nie trafiło do adresata ;) do analizy tekstów polecam sprawdzenie Słowosieci, zajmuje się nią Clarin-PL (mają dobry kanał na YouTube) w tym roku szykują podobno rewolucję w analizie tekstów w języku polskim. Polecam przerzucenie ich biblioteki do bazy danych i analizę w sql ewentualnie używanie ich narzędzi choć tego nie próbowałam Miłego dnia :)MK Wysłane z iPhone'aWiadomość napisana przez Jan Rybicki ***@***.***> w dniu 19.07.2023, o godz. 08:11:﻿
[WybuchWMózgu]

Ten zarośnięty typ podpisany “Filip Strzałka” jest kobietą Martą Kliszko?! Wiem, że jestem człowiekiem starej daty (ur. 1963), ale żeby aż tak?



Co się dzieje?



Wstrząśnięty,



Jan Rybicki



 







 



From: TheOffiec ***@***.***> 

Sent: Wednesday, July 19, 2023 8:04 AM

To: philvec/sentimentPL ***@***.***>

Cc: Jan Rybicki ***@***.***>; Author ***@***.***>

Subject: Re: [philvec/sentimentPL] Kontakt? (Issue #4)



 



Dzień dobry, zupełnie nie rozumiem dlaczego wszyscy zakładają łącznie z promotorem ze jestem facetem (dzień przed obroną chyba odkrył ze jestem kobietą) ;) istotnie ruszyłam SentimentPl ale ostatecznie go nie użyłam i zdecydowałam się na slowosieć, której wyniki i tak przedstawiłam bardziej jako ciekawostkę. Z SentimentPl miałam problem w interpretacji wyniku jeśli dobrze pamietam, ale nie pamietam czy udało mi się dotrzeć do dokumentacji, na podobnej pracy zauważyłam ze autorzy którzy skorzystali z SentimentPl  większość analizowanych słów zakwalifikowali jako słowa negatywne - prawdopodobnie brak dokumentacji.  Temat analizy języka dopiero zaczynam zgłębiać wiec prawdopodobnie mogłam coś przeoczyć ;)Z pozdrowieniamiMarta KliszkoWysłane z iPhone'aWiadomość napisana przez Jan Rybicki ***@***.*** <mailto:***@***.***> > w dniu 19.07.2023, o godz. 07:17:﻿ 

Szanowny Panie, 

Przepraszam, że porozumiewam się z Panem w ten sposób, ale jak inaczej. Odkryłem Pana sentimentPL i używam go do analizy wydźwięku zgromadzonych przeze mnie 10000 polskich tekstów literackich (pełne powieści, dramaty, zbiorki poezji). Jak rozumiem, nie jest to całkiem pozbawione sensu, bo trenował Pan model na "Wolnych lekturach". Z przyjemnościa poznałbym więcej szczegółów - może moglibyśmy umówić się na jakąś rozmowę, bo wydaje mi się, że wyniki mogą być całkiem publikowalne? 

Z serdecznymi pozdrowieniami, 

Jan Rybicki 

Jagiellońskie Centrum Humanistyki Cyfrowej 

https://www.uj.edu.pl/web/jchc

**Comment by philvec** [comment]
Dzień dobry
Tu Filip Strzałka (ten zarośnięty typ 😀 ) Dziękuję za kontakt. Chętnie porozmawiam o szczegółach i pomogę na ile będę w stanie - projekt był realizowany 2 lata temu, zapewne potrzebowałby odświeżenia. 

Aby wyklarować już poruszone kwestie: sentimentPL zawiera model językowy HerBERT od allegro, wytrenowany na zbiorze zawierającym m.in. bazę WolneLektury. Z kolei część modelu odpowiedzialna za określenie wydźwięku tekstu zwektoryzowanego przez model HerBERT, była trenowana na zbiorze udostępnionym przez wspomniany zespół ClarinPL, z którego pochodził również opiekun projektu.

Proszę o kontakt na adres e-mail : strzalkafilip@gmail.com
Pozdrawiam serdecznie
Filip Strzałka.

**Comment by jkrybicki** [comment]
Uff.

JR
